import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('accounting analysis reports (#152)', () => {
  it('exposes Tax Returns, Unrealized Currencies, Invoice Analysis, Analytic, Executive, and Budget reports', () => {
    const nav = readFileSync(resolve(__dirname, '../../../../config/nav.ts'), 'utf8')
    const router = readFileSync(resolve(__dirname, '../../../../router/index.ts'), 'utf8')
    const sidebar = readFileSync(resolve(__dirname, '../../../../layouts/AppSidebar.vue'), 'utf8')
    const access = readFileSync(resolve(__dirname, '../../../../router/access.ts'), 'utf8')
    const catalog = readFileSync(resolve(__dirname, '../../../../config/reportsCatalog.ts'), 'utf8')
    const api = readFileSync(resolve(__dirname, '../../../../api/useAccountingAnalysis.ts'), 'utf8')
    const page = readFileSync(resolve(__dirname, '../AccountingAnalysisPage.vue'), 'utf8')

    expect(nav).toContain("name: 'Tax Returns'")
    expect(nav).toContain('/accounting/tax-returns')
    expect(nav).toContain("name: 'Unrealized Currencies'")
    expect(nav).toContain('/accounting/unrealized-currencies')
    expect(nav).toContain("name: 'Invoice Analysis'")
    expect(nav).toContain('/accounting/invoice-analysis')
    expect(nav).toContain("name: 'Analytic Report'")
    expect(nav).toContain('/accounting/analytic-report')
    expect(nav).toContain("name: 'Executive Summary'")
    expect(nav).toContain('/accounting/executive-summary')
    expect(nav).toContain("name: 'Budget Report'")
    expect(nav).toContain('/accounting/budget-report')
    expect(router).toContain("path: 'tax-returns'")
    expect(router).toContain("path: 'unrealized-currencies'")
    expect(router).toContain("path: 'invoice-analysis'")
    expect(router).toContain("path: 'analytic-report'")
    expect(router).toContain("path: 'executive-summary'")
    expect(router).toContain("path: 'budget-report'")
    expect(access).toContain('/accounting/tax-returns')
    expect(access).toContain('/accounting/unrealized-currencies')
    expect(sidebar).toContain('sidebar-tax-returns')
    expect(sidebar).toContain('sidebar-budget-report')
    expect(catalog).toContain('/accounting/tax-returns')
    expect(catalog).toContain('/accounting/invoice-analysis')
    expect(api).toContain('/reports/tax-returns')
    expect(api).toContain('/reports/review/unrealized-currencies')
    expect(api).toContain('/reports/invoice-analysis')
    expect(api).toContain('/reports/analytic-report')
    expect(api).toContain('/reports/executive-summary')
    expect(api).toContain('/reports/budget-report')
    expect(page).toContain('analysis-year')
    expect(page).toContain('analysis-as-of')
    expect(page).not.toContain('router.push(`')
  })
})
