import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('project tasks workspace (#154)', () => {
  it('exposes My/All Tasks, Tasks Analysis, and Customer Ratings', () => {
    const nav = readFileSync(resolve(__dirname, '../../../config/nav.ts'), 'utf8')
    const router = readFileSync(resolve(__dirname, '../../../router/index.ts'), 'utf8')
    const sidebar = readFileSync(resolve(__dirname, '../../../layouts/AppSidebar.vue'), 'utf8')
    const access = readFileSync(resolve(__dirname, '../../../router/access.ts'), 'utf8')
    const catalog = readFileSync(resolve(__dirname, '../../../config/reportsCatalog.ts'), 'utf8')
    const workspace = readFileSync(resolve(__dirname, '../TaskWorkspacePage.vue'), 'utf8')
    const analysis = readFileSync(resolve(__dirname, '../TaskAnalysisPage.vue'), 'utf8')
    const ratings = readFileSync(resolve(__dirname, '../CustomerRatingListPage.vue'), 'utf8')
    const form = readFileSync(resolve(__dirname, '../CustomerRatingFormPage.vue'), 'utf8')
    const apiTasks = readFileSync(resolve(__dirname, '../../../api/useProjectTasks.ts'), 'utf8')
    const apiRatings = readFileSync(resolve(__dirname, '../../../api/useCustomerRatings.ts'), 'utf8')
    const apiAnalysis = readFileSync(resolve(__dirname, '../../../api/useTaskAnalysis.ts'), 'utf8')

    expect(nav).toContain("name: 'My Tasks'")
    expect(nav).toContain('/projects/my-tasks')
    expect(nav).toContain("name: 'All Tasks'")
    expect(nav).toContain('/projects/tasks')
    expect(nav).toContain("name: 'Tasks Analysis'")
    expect(nav).toContain("name: 'Customer Ratings'")
    expect(router).toContain("path: 'projects/my-tasks'")
    expect(router).toContain("path: 'projects/tasks'")
    expect(router).toContain("path: 'projects/tasks-analysis'")
    expect(router).toContain("path: 'projects/customer-ratings'")
    expect(router).toContain("path: 'my-tasks'")
    expect(router).toContain("path: 'all-tasks'")
    expect(router).toContain("path: 'tasks-analysis'")
    expect(router).toContain("path: 'customer-ratings'")
    expect(access).toContain('/projects/my-tasks')
    expect(access).toContain('/projects/tasks-analysis')
    expect(access).toContain('/projects/customer-ratings')
    expect(sidebar).toContain('sidebar-my-tasks')
    expect(sidebar).toContain('sidebar-all-tasks')
    expect(sidebar).toContain('sidebar-tasks-analysis')
    expect(sidebar).toContain('sidebar-customer-ratings')
    expect(catalog).toContain('/projects/tasks-analysis')
    expect(catalog).toContain('/projects/customer-ratings')
    expect(workspace).toContain('My Tasks')
    expect(workspace).toContain('All Tasks')
    expect(analysis).toContain('Tasks Analysis')
    expect(ratings).toContain('New Rating')
    expect(form).toContain('customer-rating-save')
    expect(apiTasks).toContain('/tasks/my')
    expect(apiRatings).toContain("resourceName: 'customer-ratings'")
    expect(apiAnalysis).toContain('/reports/tasks-analysis')
    expect(workspace).not.toContain('router.push(`')
    expect(ratings).not.toContain('router.push(`')
    expect(form).not.toContain('router.push(`')
  })
})
